name: Project Publishing
permissions:
  contents: read
  packages: write
on:
  push:
    paths: [ 'ChmlFrp.SDK/**', 'ChmlFrp.SDK.Services/**' , 'ChmlFrp.SDK.Test/**' , '**/Publish.yml' ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-cache
      - run: dotnet publish ChmlFrp.SDK.Test\ChmlFrp.SDK.Test.csproj -r win-x64 -p:PublishAot=true
      - uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            **/publish
            !**/*.pdb
      - run: |
          dotnet pack ChmlFrp.SDK\ChmlFrp.SDK.csproj
          dotnet pack ChmlFrp.SDK.Services\ChmlFrp.SDK.Services.csproj
          dotnet nuget push **\ChmlFrp.SDK.*.nupkg --source https://nuget.pkg.github.com/Qianyiaz/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETKEY }}  --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.Services.*.nupkg --source https://nuget.pkg.github.com/Qianyiaz/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.Services.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETKEY }} --skip-duplicate
