name: Project Publishing
permissions:
  contents: read
  packages: write
  id-token: write
on:
  push:
    paths: [ 'src/**' , '**/Publish.yml' ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github
            src
      - uses: NuGet/login@v1
        id: login
        with:
          user: Qusay
      - run: |
          dotnet pack src\ChmlFrp.SDK\ChmlFrp.SDK.csproj
          dotnet pack src\ChmlFrp.SDK.Services\ChmlFrp.SDK.Services.csproj
          dotnet nuget push **\ChmlFrp.SDK.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.Services.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.*.nupkg --source https://nuget.pkg.github.com/Qianyiaz/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          dotnet nuget push **\ChmlFrp.SDK.Services.*.nupkg --source https://nuget.pkg.github.com/Qianyiaz/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
